### ISSUE TITLE
[BUG] Missing Virtwifi. (Network is not working)

### ISSUE THREAD

**Issue by Noir16** [MustardChef/WSABuilds#213]
### Describe the bug | 描述一下这个错误

Virtwifi doesn't exist, so it's impossible to connect to the network.
![スクリーンショット 2023-10-22 160637](https://github.com/MustardChef/WSABuilds/assets/112380807/9a69482e-4ea9-4ac7-8497-75f8b90edae1)

### Steps to reproduce the issue | 重现该问题的步骤

Unkown

### Expected behaviour | 预期的行为

WSA is networked via Virtwifi.

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2309.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon (Windows 11)

### Windows build number | Windows构建号

22631.2338

### PC Specification | 个人电脑规格

CPU: Intel Core i7-10750H
RAM: 16GB
GPU: Intel UHD Graphics / NVIDIA Geforce GTX1650 Max-Q
Ethernet: Realtek RTL8153 / Intel Wi-Fi6 AX201

**Comment by MustardChef** [comment]
Yeah, it has changed in recent version of WSA.

**Comment by MustardChef** [comment]
@Noir16 Are you using a Antivirus firewall?

**Comment by Noir16** [comment]
@MustardChef I'm not Anti-Malware Software (Disable Windows Defender too), but I'm using portmaster firewall. However, Portmaster told me that it does not attempt to block traffic to the VM.
I assumed it was probably an issue with the Mullvad VPN I was using, so I tried throwing an exception, but Internet still didn't work on the WSA.

**Comment by MustardChef** [comment]
> @MustardChef I'm not Anti-Malware Software (Disable Windows Defender too), but I'm using portmaster firewall. However, Portmaster told me that it does not attempt to block traffic to the VM. I assumed it was probably an issue with the Mullvad VPN I was using, so I tried throwing an exception, but Internet still didn't work on the WSA.

Have you tried changing the "Local Network Access" setting?

**Comment by Noir16** [comment]
I tried, but there's no response.

**Comment by Snowlights2022** [comment]
Hello, your problem may come from Microsoft's official netgate used by WSA. It's name is FSE switch, and it is in Hyper-V manager of Windows, under choice Virtual Switch. To solve your problem, you can go to windows settings, find app named Windows Subsystem for Android (or like that), then click "repair" button. After this, restart wsa, and the problem should be solved. By the way,  #165  has the same condition. I can't understand why ms do this change.   :(

**Comment by AdamTurock** [comment]
Thank you.  I performed the actions you suggested.  I also cleared the App cache, stopped WSA, and rebooted my computer.

I still get the same issue.  I attached some screenshots for clarity.

[ScreenShotWSA.pdf](https://github.com/MustardChef/WSABuilds/files/13460567/ScreenShotWSA.pdf)
[ScreenshotPhone.pdf](https://github.com/MustardChef/WSABuilds/files/13460568/ScreenshotPhone.pdf)

**Comment by d0j1a1701** [comment]
Found a possible issue and provided a solution. #165

**Comment by unclefive55** [comment]
> Found a possible issue and provided a solution. #165

Not working bcz no fakewifi
