### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by terrytw** [MustardChef/WSABuilds#39]
Hi dear dev,

I am on Windows 10 22H2 19045.2604, WSA_2301.40000.7.0_x64_Release-Nightly-with-magisk-2717feac.25209.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10.

There seems to be a network issue. 

First of all, sometimes it takes tens of minutes to an hour before I get the "Fakewifi" connection. In this period, some app does not even open, some apps open but does not work because no internet, and some apps get internet somehow....

Then, after several days, I start to get WSAupdate error messages when shutting down. Then, some days later, when I boot up, WSA simply stops to work. It shows WSAclient error 0x00000505. (I will try to get more details on these error messages next time they pop up)

I figured out that if I disable network adaptor, WSA would start to work again. 

So weird...

**Comment by MustardChef** [comment]
@terrytw Hello, thank you for the report. WSA can behave very weirdly on Windows 10. Could you confirm that this issue still exists in the latest version of WSA, which is 2302.40000.6.0.

**Comment by terrytw** [comment]
Hi it persists in the latest version, because after the problem occurred, I updated to latest version and it is still the same.

**Comment by MustardChef** [comment]
> Hi it persists in the latest version, because after the problem occurred, I updated to latest version and it is still the same. And after update, the WSAclient window becomes English instead of my native language, so I uninstalled it.

Could you please join the Discord, so I can try some methods to see if they fix your issue.

**Comment by YT-Advanced** [comment]
Look like the DLL file patch didn't loaded. Can you go to WSA extract path then check the winhttp.dll

**Comment by terrytw** [comment]
Hi thanks for the suggestion. I can find winhttp.dll in the WsaClient folder. 
MustardChef has suggested me to disable to enable hyper v. I will see if the problem occurs or not after this. If it occurs again, I will report here.

**Comment by MustardChef** [comment]
@terrytw Since the language support issue was fixed in v2302.40000.8.0, can you try updating to that version.

**Comment by terrytw** [comment]
@MustardChef Thanks, I want to stay in old version for a few more days, just to see if the disable and enable fixes it. I will definitely update and test again too.

**Comment by terrytw** [comment]
Update: it happened again. So the disable and enable did not work. I uninstalled old version and installed new version. 
I will update later, whether it is fixed or not.

**Comment by MustardChef** [comment]
> @terrytw Can you try to turn off all of your antivirus provider and test again. If it not work, you can test my own build in the link below (It support both Windows 10 and 11) :D https://github.com/YT-Advanced/WSA-Script/releases/latest
> 
> Some infomation about the error code: winerror.h: 0x00000505 ERROR_DELAY_LOAD_FAILED An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed.

Hmm, but will using the builds from your builds really make a difference? The same MagiskOnWSALocal script is used and so there should not be any differing results regarding the issue that @terrytw is facing.

**Comment by terrytw** [comment]
I will test WSA_2302.40000.9.0 for now. 

I'd like to add a few more findings as well. When it breaks down, the first symptom is that WSA will not start at all, there is a small windows saying WSA is starting, but then it just disappears, the app does not show up. If you click on the app, it is the WSA is starting window again, before it quickly disappears. Once this happens, if I reboot a few times, or wait a few days, then I get the 0x00000505 error. 

Also, aside from the WSAupdate error, I also get a WSAcrashuploader error. Both of them show up during shutdown, so I did not see what the content of the error message.

**Comment by YT-Advanced** [comment]
> > @terrytw Can you try to turn off all of your antivirus provider and test again. If it not work, you can test my own build in the link below (It support both Windows 10 and 11) :D https://github.com/YT-Advanced/WSA-Script/releases/latest
> > Some infomation about the error code: winerror.h: 0x00000505 ERROR_DELAY_LOAD_FAILED An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed.
> 
> Hmm, but will using the builds from your repo really make a difference? The same MagiskOnWSALocal script and WSAPatch patching method is used and so there should not be any differing results regarding the issue that @terrytw is facing.

It has some different in the install script

**Comment by MustardChef** [comment]
> > > @terrytw Can you try to turn off all of your antivirus provider and test again. If it not work, you can test my own build in the link below (It support both Windows 10 and 11) :D https://github.com/YT-Advanced/WSA-Script/releases/latest
> > > Some infomation about the error code: winerror.h: 0x00000505 ERROR_DELAY_LOAD_FAILED An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed.
> > 
> > 
> > Hmm, but will using the builds from your repo really make a difference? The same MagiskOnWSALocal script and WSAPatch patching method is used and so there should not be any differing results regarding the issue that @terrytw is facing.
> 
> It has some different in the install script

What specifically is different?

**Comment by YT-Advanced** [comment]
@MustardChef sometime, when you mannually patch DLL from cinit, it can corrupt and cause error. My script have a checksum for DLL and also for WSA zip file. So if the DLL is corruption, it will auto redownload and patch again.

@terrytw also can you tell me how much RAM do you have ? And did you turn off the antivirus provider before start

**Comment by MustardChef** [comment]
Hmm, I see. I have also implemented a Python script to confirm the checksum of the DLLs, when I download them. Therefore, corrupted DLLs should not be an issue

**Comment by terrytw** [comment]
@YT-Advanced Hi 
1. I have 16G RAM. Usually there are plenty available. I have not played any games for several months. 
2. I have not disabled anti-virus. I use Huorong, which is not so intrusive as something like Kaspersky. Also, I have used Huorong together with the MagiskonWsaLocal on Windows 11 for several months, there isn't any problem.

**Comment by YT-Advanced** [comment]
> @YT-Advanced Hi 
> 1. I have 16G RAM. Usually there are plenty available. I have not played any games for several months. 
> 2. I have not disabled anti-virus. I use Huorong, which is not so intrusive as something like Kaspersky. Also, I have used Huorong together with the MagiskonWsaLocal on Windows 11 for several months, there isn't any problem.

Hmm, look like you have used Windows 10 version on Windows 11 computer so that is why you can't use

**Comment by terrytw** [comment]
> > @YT-Advanced Hi
> > 
> > 1. I have 16G RAM. Usually there are plenty available. I have not played any games for several months.
> > 2. I have not disabled anti-virus. I use Huorong, which is not so intrusive as something like Kaspersky. Also, I have used Huorong together with the MagiskonWsaLocal on Windows 11 for several months, there isn't any problem.
> 
> Hmm, now maybe you should upgrade to Windows 11 or install KB5022834

I am on 19045.2604, so I think my system already has KB5022834 included.
Upgrading to Windows 11 would OFC evade the problem, but the problem is not fixed.

**Comment by YT-Advanced** [comment]
0x00007FFE216FCD29 is a hex location of the RAM or maybe the DLL. But now I think you should test orginal WSA version in [WSAOrginalPackage](https://github.com/MrKristofere/WSA-Original-Packages/releases/download/WSA-Original-Packages/MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_neutral___8wekyb3d8bbwe.Msixbundle) to check where error come from.

**Comment by YT-Advanced** [comment]
@terrytw also share the log from Event Viewer for me please

**Comment by terrytw** [comment]
OK, as I said, I will keep testing WSA_2302.40000.9.0. If problem occurs again, I will show you the event view information.

**Comment by terrytw** [comment]
Update: first I managed to remember the crash error code during shutdown: 0xc00000142
Second the same problem occurred for WSA_2302.40000.9.0.
Last there is this application error message in event viewer: (translated from my native language)

error application name: WsaClient.exe，Ver: 2302.40000.9.0，Timestamp: 0x6421f118
Error module name: KERNELBASE.dll，Ver: 10.0.19041.2546，Timestamp: 0xe8e9ac9b
Error code: 0x00000505
Error offset: 0x000000000002cd29
Error process ID: 0x23cc
Error application startup tiime: 0x01d96ba8e5a22393
Error application path: C:\Program Files\Windows Subsystem for Android\WsaClient\WsaClient.exe
Error module path: C:\Windows\System32\KERNELBASE.dll
Report ID: a99999d6-63a5-4839-bcb6-ce9d770cf5a1
Error app package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe
Error package relative application ID: App

**Comment by MustardChef** [comment]
I also agree with @YT-Advanced with regards to this issue. Seems like its a problem with the Windows OS itself, rather than WSA.

**Comment by terrytw** [comment]
OK, I will try to reinstall Windows. Thanks for both of you! I will close this for now, since both of you think it is an OS issue.

**Comment by MustardChef** [comment]
> OK, I will try to reinstall Windows. Thanks for both of you! I will close this for now, since both of you think it is an OS issue.

Keep us updated on whether or not a reinstallation of Windows fixes the issue.

**Comment by terrytw** [comment]
I don't know if it is relevant or not, there is another error message:

Error application name: GSKServer.exe，Ver: 2302.40000.9.0，Timestamp: 0x6421f0ef
Error module name: gfxstream_backend.dll，Ver: 0.0.0.0，Timestamp: 0x63f6bbdf
Error code: 0x00000505
Error offset: 0x0000000000135800
Error process ID: 0x2a7c
Error application startup tiime: 0x01d96bbc6539e2eb
Error application path: C:\Program Files\Windows Subsystem for Android\GSKServer\GSKServer.exe
Error module path: C:\Program Files\Windows Subsystem for Android\gfxstream_backend.dll
Report ID: 0976d9b0-03c3-4940-aa93-5fa74cadfdc9
Error app package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe
Error package relative application ID: App

**Comment by terrytw** [comment]
> > OK, I will try to reinstall Windows. Thanks for both of you! I will close this for now, since both of you think it is an OS issue.
> 
> Keep us updated on whether or not a reinstallation of Windows fixes the issue.

Yes I will update my findings.

**Comment by terrytw** [comment]
Update:

It seems that reinstalling windows does fix the issue.

**Comment by MustardChef** [comment]
> Update:
> 
> It seems that reinstalling windows does fix the issue.

Great to hear!
